package com.weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-06-02T22:54:27.972+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "WeatherWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherWebServiceSoap {

    @WebResult(name = "getWeatherbyCityNameResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getWeatherbyCityName", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetWeatherbyCityName")
    @WebMethod(action = "http://WebXml.com.cn/getWeatherbyCityName")
    @ResponseWrapper(localName = "getWeatherbyCityNameResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetWeatherbyCityNameResponse")
    public com.weather.ArrayOfString getWeatherbyCityName(
        @WebParam(name = "theCityName", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theCityName
    );

    @WebResult(name = "getSupportDataSetResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportDataSet", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetSupportDataSet")
    @WebMethod(action = "http://WebXml.com.cn/getSupportDataSet")
    @ResponseWrapper(localName = "getSupportDataSetResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetSupportDataSetResponse")
    public com.weather.GetSupportDataSetResponse.GetSupportDataSetResult getSupportDataSet();

    @WebResult(name = "getWeatherbyCityNameProResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getWeatherbyCityNamePro", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetWeatherbyCityNamePro")
    @WebMethod(action = "http://WebXml.com.cn/getWeatherbyCityNamePro")
    @ResponseWrapper(localName = "getWeatherbyCityNameProResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetWeatherbyCityNameProResponse")
    public com.weather.ArrayOfString getWeatherbyCityNamePro(
        @WebParam(name = "theCityName", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theCityName,
        @WebParam(name = "theUserID", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theUserID
    );

    @WebResult(name = "getSupportCityResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportCity", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetSupportCity")
    @WebMethod(action = "http://WebXml.com.cn/getSupportCity")
    @ResponseWrapper(localName = "getSupportCityResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetSupportCityResponse")
    public com.weather.ArrayOfString getSupportCity(
        @WebParam(name = "byProvinceName", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String byProvinceName
    );

    @WebResult(name = "getSupportProvinceResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getSupportProvince", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetSupportProvince")
    @WebMethod(action = "http://WebXml.com.cn/getSupportProvince")
    @ResponseWrapper(localName = "getSupportProvinceResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.weather.GetSupportProvinceResponse")
    public com.weather.ArrayOfString getSupportProvince();
}
