package com.newtouch.webservice.testreportrelease;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-06-06T15:00:58.426+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "TestReportRelease", 
                  wsdlLocation = "file:/D:/git/TestDemo/asmxWebservice/src/main/resources/TestReportRelease.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class TestReportRelease_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "TestReportRelease");
    public final static QName TestReportReleaseSoap12 = new QName("http://tempuri.org/", "TestReportReleaseSoap12");
    public final static QName TestReportReleaseSoap = new QName("http://tempuri.org/", "TestReportReleaseSoap");
    public final static QName TestReportReleaseHttpGet = new QName("http://tempuri.org/", "TestReportReleaseHttpGet");
    public final static QName TestReportReleaseHttpPost = new QName("http://tempuri.org/", "TestReportReleaseHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/git/TestDemo/asmxWebservice/src/main/resources/TestReportRelease.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestReportRelease_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/git/TestDemo/asmxWebservice/src/main/resources/TestReportRelease.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestReportRelease_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestReportRelease_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestReportRelease_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestReportRelease_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestReportRelease_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestReportRelease_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TestReportReleaseSoap
     */
    @WebEndpoint(name = "TestReportReleaseSoap12")
    public TestReportReleaseSoap getTestReportReleaseSoap12() {
        return super.getPort(TestReportReleaseSoap12, TestReportReleaseSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestReportReleaseSoap
     */
    @WebEndpoint(name = "TestReportReleaseSoap12")
    public TestReportReleaseSoap getTestReportReleaseSoap12(WebServiceFeature... features) {
        return super.getPort(TestReportReleaseSoap12, TestReportReleaseSoap.class, features);
    }
    /**
     *
     * @return
     *     returns TestReportReleaseSoap
     */
    @WebEndpoint(name = "TestReportReleaseSoap")
    public TestReportReleaseSoap getTestReportReleaseSoap() {
        return super.getPort(TestReportReleaseSoap, TestReportReleaseSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestReportReleaseSoap
     */
    @WebEndpoint(name = "TestReportReleaseSoap")
    public TestReportReleaseSoap getTestReportReleaseSoap(WebServiceFeature... features) {
        return super.getPort(TestReportReleaseSoap, TestReportReleaseSoap.class, features);
    }
    /**
     *
     * @return
     *     returns TestReportReleaseHttpGet
     */
    @WebEndpoint(name = "TestReportReleaseHttpGet")
    public TestReportReleaseHttpGet getTestReportReleaseHttpGet() {
        return super.getPort(TestReportReleaseHttpGet, TestReportReleaseHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestReportReleaseHttpGet
     */
    @WebEndpoint(name = "TestReportReleaseHttpGet")
    public TestReportReleaseHttpGet getTestReportReleaseHttpGet(WebServiceFeature... features) {
        return super.getPort(TestReportReleaseHttpGet, TestReportReleaseHttpGet.class, features);
    }
    /**
     *
     * @return
     *     returns TestReportReleaseHttpPost
     */
    @WebEndpoint(name = "TestReportReleaseHttpPost")
    public TestReportReleaseHttpPost getTestReportReleaseHttpPost() {
        return super.getPort(TestReportReleaseHttpPost, TestReportReleaseHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestReportReleaseHttpPost
     */
    @WebEndpoint(name = "TestReportReleaseHttpPost")
    public TestReportReleaseHttpPost getTestReportReleaseHttpPost(WebServiceFeature... features) {
        return super.getPort(TestReportReleaseHttpPost, TestReportReleaseHttpPost.class, features);
    }

}
