package com.newtouch.webservice.testreportrelease;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-06-06T15:00:58.420+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TestReportReleaseHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestReportReleaseHttpPost {

    /**
     * 检验报告发布
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod
    public java.lang.String testReportRelease(
        @WebParam(partName = "xml", name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );

    /**
     * 心电图相关接口
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "PlatForm_ECG_Service")
    public java.lang.String platFormECGService(
        @WebParam(partName = "xml", name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );

    /**
     * 唐氏筛查相关接口
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "PlatForm_TSSC_Service")
    public java.lang.String platFormTSSCService(
        @WebParam(partName = "xml", name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );
}
