package com.newtouch.webservice.patientbasicinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2018-06-06T15:02:48.140+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PatientBasicInfoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PatientBasicInfoSoap {

    /**
     * 病人基本信息
     */
    @WebResult(name = "patientBasicInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "patientBasicInfo", targetNamespace = "http://tempuri.org/", className = "com.newtouch.webservice.patientbasicinfo.PatientBasicInfo")
    @WebMethod(action = "http://tempuri.org/patientBasicInfo")
    @ResponseWrapper(localName = "patientBasicInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.newtouch.webservice.patientbasicinfo.PatientBasicInfoResponse")
    public java.lang.String patientBasicInfo(
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );

    /**
     * 病人基本信息(对外)
     */
    @WebResult(name = "patientBasicInfoOutResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "patientBasicInfoOut", targetNamespace = "http://tempuri.org/", className = "com.newtouch.webservice.patientbasicinfo.PatientBasicInfoOut")
    @WebMethod(action = "http://tempuri.org/patientBasicInfoOut")
    @ResponseWrapper(localName = "patientBasicInfoOutResponse", targetNamespace = "http://tempuri.org/", className = "com.newtouch.webservice.patientbasicinfo.PatientBasicInfoOutResponse")
    public java.lang.String patientBasicInfoOut(
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );

    /**
     * 病人基本信息(唐筛)
     */
    @WebResult(name = "patientDetailInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "patientDetailInfo", targetNamespace = "http://tempuri.org/", className = "com.newtouch.webservice.patientbasicinfo.PatientDetailInfo")
    @WebMethod(action = "http://tempuri.org/patientDetailInfo")
    @ResponseWrapper(localName = "patientDetailInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.newtouch.webservice.patientbasicinfo.PatientDetailInfoResponse")
    public java.lang.String patientDetailInfo(
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );
}
